import { useEffect, type ReactNode } from "react";
import { useTranslation } from "react-i18next";

// Some student components predate i18n and still contain static Chinese copy.
// This bridge keeps those legacy labels in sync while they are progressively
// moved to translation keys. It never touches messages generated by users/models.
const zhToEn: Record<string, string> = {
  "NLP 学习助手": "NLP Learning Assistant", "新建对话": "New chat", "新建分类": "New category", "搜索": "Search", "设置": "Settings", "未分类": "Uncategorized", "归档对话": "Archived chats", "返回最近对话": "Recent chats", "新的学习对话": "New learning chat", "重命名": "Rename","归档": "Archive", "移出归档": "Unarchive", "删除": "Delete", "移动到分类": "Move to category", "请输入分类名称": "Enter a category name", "重命名分类": "Rename category", "关闭侧栏": "Close sidebar", "展开侧栏": "Expand sidebar", "折叠侧栏": "Collapse sidebar",
  "NLP 基础": "NLP Fundamentals", "文本分类": "Text Classification", "词向量与表示学习": "Word Vectors & Representation Learning", "大语言模型": "Large Language Models", "入门": "Beginner", "进阶": "Intermediate", "深入": "Advanced", "讲解模式": "Explanation mode", "引导模式": "Guided mode", "练习模式": "Practice mode", "复习模式": "Review mode",
  "偏好设置": "Preferences", "学习空间": "Learning space", "通用": "General", "外观": "Appearance", "对话与流式": "Chat & streaming", "学习体验": "Learning experience", "数据与隐私": "Data & privacy", "高级设置": "Advanced", "意见反馈": "Feedback", "版本与更新": "Version & updates", "界面语言": "Interface language", "阅读语言": "Reading language", "当前版本": "Current version", "本次更新与修复": "Updates & fixes", "提交你的建议": "Share your feedback", "发布意见": "Submit feedback",
  "版本号随构建自动同步": "Version synced from build", "来自当前发布构建，无需手动维护。": "Injected from the release build; no manual maintenance.", "由开发者工作台维护，学生端实时同步。": "Maintained in the developer workspace and synced to students.", "暂无已发布的更新说明。": "No published release notes yet.", "无法读取更新说明，请稍后重试。": "Couldn't load release notes; please try again.", "正在读取…": "Loading…", "重新加载": "Reload",
  "无法读取当前版本，请稍后重试。": "Couldn't load the current version; please try again.", "正在读取最近一次发布。": "Loading the latest release.", "最近一次已发布版本，学生端当前生效。": "Latest published version currently active for students.", "还没有已发布版本。": "No published version yet.", "展示最近一次发布的更新内容，历史版本不会挤在当前页面。": "Showing the latest release; older versions stay out of this view.", "发布日期待补充": "Release date pending",
  "当前身份不支持提交反馈": "Feedback is not available for your role",
  "浅色": "Light", "深色": "Dark", "跟随系统": "System", "前往开发者工作台": "Open developer workspace", "进入教师模式": "Open teacher mode", "已是当前版本": "You're up to date", "学习记录": "Learning record", "已连接": "Connected", "正在连接": "Connecting", "正在恢复连接": "Reconnecting", "离线": "Offline",
  "本次学习": "This learning session", "学习目标": "Learning goal", "已涉及概念": "Concepts covered", "完成一次对话后自动整理": "Generated automatically after a completed chat", "待复习：": "Review later: ", "学习进度": "Learning progress", "对话摘要": "Chat summary", "尚未生成学习摘要。": "No learning summary yet.", "巩固练习": "Practice", "生成练习": "Generate exercise", "检查理解": "Check understanding", "导出 Markdown 学习报告": "Export Markdown learning report",
  "仅显示学生模式可安全调整的选项。": "Only options that are safe to adjust in student mode are shown.",
  "模型、工具与运行时配置在开发者工作台统一管理。": "Models, tools, and runtime settings are managed in the developer workspace.",
  "修改会立即保存，并在下次打开时恢复。": "Changes are saved immediately and restored the next time you open settings.",
  "语言偏好会同步保存到本地后端，并立即切换学生模式的界面语言。": "Your language preference is saved to the local backend and applied immediately.",
  "当前为单一同域学习空间；课程、班级和学生账号将在后续接入。": "This is currently a single learning workspace; courses, classes, and student accounts will be added later.",
  "默认工作空间：": "Default workspace: ",
  "偏好管理": "Preference management",
  "将界面和学习偏好恢复为初始状态，不会删除对话或学习记录。": "Restore interface and learning preferences without deleting chats or learning records.",
  "恢复默认偏好": "Restore default preferences",
  "恢复语言、主题、阅读字号、动态效果及其他偏好。": "Restore language, theme, reading size, motion, and other preferences.",
  "恢复默认": "Restore defaults",
  "主题": "Theme",
  "跟随系统，或固定为浅色、深色主题。": "Follow the system theme or use a fixed light or dark theme.",
  "阅读体验": "Reading experience",
  "调整学习内容字号，并减少非必要的界面动态效果。": "Adjust learning-content text size and reduce unnecessary motion.",
  "回答内容字号": "Answer text size",
  "仅调整聊天回答、题目和学习内容。": "Only affects chat answers, exercises, and learning content.",
  "较小": "Small",
  "标准": "Standard",
  "较大": "Large",
  "减少动态效果": "Reduce motion",
  "减少侧栏、弹窗与内容出现时的动画。": "Reduce animations in sidebars, dialogs, and content.",
  "恢复默认偏好？": "Restore default preferences?",
  "将恢复语言、主题、阅读字号、动态效果及其他偏好，不会删除对话或学习记录。": "This restores language, theme, reading size, motion, and other preferences without deleting chats or learning records.",
  "关闭设置": "Close settings",
    "取消": "Cancel",
    "回答呈现": "Answer presentation",
  "控制实时回答在页面上的呈现方式。": "Control how real-time answers are presented on the page.",
  "显示思考过程": "Show reasoning",
  "显示模型返回的推理流；教学回答本身不受影响。": "Show the model's reasoning stream without changing the teaching response.",
  "流式渲染节奏": "Streaming pace",
  "较快更实时，较慢更稳定": "Faster feels more immediate; slower is more stable.",
  "即时": "Instant",
  "平衡（30 ms）": "Balanced (30 ms)",
  "平滑（80 ms）": "Smooth (80 ms)",
  "快捷操作": "Quick actions",
  "发送消息后，可以在学习记录中生成练习、标记待复习概念，或导出 Markdown 学习报告。": "After sending a message, you can generate exercises, mark concepts for review, or export a Markdown learning report.",
  "对话发送：Enter；换行：Shift + Enter": "Send: Enter; new line: Shift + Enter",
  "默认学习上下文": "Default learning context",
  "主题请在聊天顶部从教师启用的目录中选择；难度和教学方式可在此设置。": "Choose a topic from the teacher-enabled catalog above the chat; set the difficulty and teaching approach here.",
  "当前主题：": "Current topic: ",
  "未选择": "Not selected",
  "难度": "Difficulty",
  "教学方式": "Teaching approach",
  "高阶": "Advanced level",
  "讲解": "Explanation",
  "苏格拉底追问": "Socratic questioning",
  "练习": "Guided practice",
  "复习": "Review session",
  "会话标题、概念、待复习标记和摘要仅存储在此浏览器；聊天内容由后端会话持久化。": "Session titles, concepts, review markers, and summaries are stored in this browser; chat content is persisted by the backend.",
  "打开右侧“学习记录”可查看进度并导出报告。": "Open Learning record on the right to view progress and export a report.",
    "数据存储": "Data storage",
  "Pro_NLP 当前采用同域、本地部署。不会从学生设置页暴露 Provider 密钥、工具权限或系统 Trace。": "Pro_NLP currently uses same-origin local deployment. Provider credentials, tool permissions, and system traces are not exposed in student settings.",
  "实时事件用于断线恢复；已完成对话可通过学习记录导出。": "Real-time events support reconnection; completed chats can be exported from Learning record.",
  "隐私说明": "Privacy",
  "学生界面只显示教学语义。运行 Trace、Token、Worker 与工具参数仅在独立的开发者监控平台可见。": "The student interface shows teaching content only. Traces, tokens, workers, and tool parameters remain in the developer monitoring platform.",
  "打开开发者工作台": "Open developer workspace",
  "开发者配置": "Developer configuration",
  "模型、Provider、MCP、Skills、工具策略、运行状态和调试数据由本产品的开发者工作台统一管理。": "Models, providers, MCP, skills, tool policies, runtime status, and debug data are managed in the developer workspace.",
  "为什么不在这里显示？": "Why isn't this shown here?",
  "学生模式避免暴露 API Key、原始 Tool JSON、工作区权限和 Agent 运维细节，以保持教学体验清晰、安全。": "Student mode hides API keys, raw tool JSON, workspace permissions, and agent operations to keep learning clear and safe.",
  "欢迎反馈功能建议、学习体验问题或内容改进方向。当前意见会持久保存在此浏览器中。": "Share feature requests, learning-experience issues, or content suggestions. Feedback is stored in this browser.",
  "例如：我希望在学习记录中增加错题复习计划……": "For example: Add a review plan for incorrect answers…",
  "已将本次意见保存在此浏览器。": "Your feedback has been saved in this browser.",
  "保存失败：": "Couldn't save: ",
};
const enToZh = Object.fromEntries(Object.entries(zhToEn).map(([zh, en]) => [en, zh]));

function translateText(root: Node, dictionary: Record<string, string>) {
  const walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT);
  const nodes: Text[] = [];
  while (walker.nextNode()) nodes.push(walker.currentNode as Text);
  for (const node of nodes) {
    const original = node.nodeValue ?? "";
    const translated = dictionary[original.trim()];
    if (translated) node.nodeValue = original.replace(original.trim(), translated);
  }
}
function translateAttributes(root: Element, dictionary: Record<string, string>) {
  const attributes = ["aria-label", "placeholder", "title"] as const;
  const elements = root.querySelectorAll<HTMLElement>("[aria-label], [placeholder], [title]");
  for (const element of elements) {
    for (const attribute of attributes) {
      const original = element.getAttribute(attribute) ?? "";
      const translated = dictionary[original.trim()];
      if (translated) {
        element.setAttribute(attribute, original.replace(original.trim(), translated));
      }
    }
  }
}
export function StaticUiBridge({ children }: { children: ReactNode }) {
  const { i18n } = useTranslation();
  useEffect(() => {
    if (location.pathname.startsWith("/developer") || location.pathname.startsWith("/teacher")) return;
    const dictionary = i18n.language.startsWith("zh") ? enToZh : zhToEn;
    const root = document.getElementById("root") ?? document.body;
    const apply = () => {
  translateText(root, dictionary);
  translateAttributes(root, dictionary);
};
    apply();
    const observer = new MutationObserver(apply);
    observer.observe(root, {
  childList: true,
  subtree: true,
  characterData: true,
  attributes: true,
  attributeFilter: ["aria-label", "placeholder", "title"],
});
    return () => observer.disconnect();
  }, [i18n.language]);
  return <>{children}</>;
}
