import type { LearningBookNavigationItem, LearningBookPage } from "@/shared/types";

const markdown = (...lines: string[]) => lines.join("\n");

export const demoLearningBookNavigation: LearningBookNavigationItem[] = [
  { topic_id: "demo-foundations", topic_name: "1. NLP 基础", knowledge_point_id: "demo-tensor", title: "张量与批次", sort_order: 1, revision: 1 },
  { topic_id: "demo-foundations", topic_name: "1. NLP 基础", knowledge_point_id: "demo-tokenization", title: "分词与词表", sort_order: 2, revision: 1 },
  { topic_id: "demo-foundations", topic_name: "1. NLP 基础", knowledge_point_id: "demo-embeddings", title: "词向量与嵌入", sort_order: 3, revision: 1 },
  { topic_id: "demo-models", topic_name: "2. 经典模型", knowledge_point_id: "demo-regression", title: "线性回归", sort_order: 1, revision: 1 },
  { topic_id: "demo-models", topic_name: "2. 经典模型", knowledge_point_id: "demo-softmax", title: "softmax 分类", sort_order: 2, revision: 1 },
  { topic_id: "demo-models", topic_name: "2. 经典模型", knowledge_point_id: "demo-cross-entropy", title: "交叉熵损失", sort_order: 3, revision: 1 },
  { topic_id: "demo-deep-learning", topic_name: "3. 深度学习实操", knowledge_point_id: "demo-mlp", title: "多层感知机", sort_order: 1, revision: 1 },
  { topic_id: "demo-deep-learning", topic_name: "3. 深度学习实操", knowledge_point_id: "demo-dropout", title: "Dropout 正则化", sort_order: 2, revision: 1 },
  { topic_id: "demo-deep-learning", topic_name: "3. 深度学习实操", knowledge_point_id: "demo-attention", title: "注意力机制", sort_order: 3, revision: 1 },
];

function demoPage(item: LearningBookNavigationItem, content_markdown: string): LearningBookPage {
  return {
    workspace_id: "demo-workspace",
    topic_id: item.topic_id,
    topic_name: item.topic_name,
    knowledge_point_id: item.knowledge_point_id,
    title: item.title,
    content_markdown,
    revision: item.revision,
  };
}

export const demoLearningBookPages: Record<string, LearningBookPage> = {
  "demo-tensor": demoPage(demoLearningBookNavigation[0], markdown(
    "## 为什么需要张量",
    "张量是 PyTorch 中承载数据的基本容器。理解形状、维度和批次，是后续搭建模型的第一步。",
    "",
    "### 创建一个小批次",
    "下面的例子用两个二维样本组成一个批次，并观察它的形状与均值。",
    "",
    "```python",
    "import torch",
    "",
    "x = torch.tensor([[1.0, 2.0], [3.0, 4.0]])",
    "print(x.shape)",
    "print(x.mean())",
    "```",
    "",
    "## 动手练习",
    "把 `x` 改成三个样本，再检查第一维是否代表批次大小。",
  )),
  "demo-tokenization": demoPage(demoLearningBookNavigation[1], markdown(
    "## 从文本到 token",
    "分词会把连续文本拆成模型可以处理的离散单元。词表则负责把每个单元映射为整数 ID。",
    "",
    "### 一个最小词表",
    "```python",
    "import torch",
    "",
    "vocab = {\"我\": 0, \"喜欢\": 1, \"学习\": 2}",
    "tokens = torch.tensor([vocab[\"我\"], vocab[\"喜欢\"], vocab[\"学习\"]])",
    "print(tokens)",
    "```",
    "",
    "## 注意事项",
    "真实项目中还需要处理未知词、填充和截断。",
  )),
  "demo-embeddings": demoPage(demoLearningBookNavigation[2], markdown(
    "## 用向量表示词语",
    "嵌入层把整数 ID 查表转换成连续向量，使相似的语义有机会在向量空间中靠近。",
    "",
    "### 创建嵌入层",
    "```python",
    "import torch",
    "from torch import nn",
    "",
    "embedding = nn.Embedding(num_embeddings=8, embedding_dim=4)",
    "word_ids = torch.tensor([0, 3, 5])",
    "print(embedding(word_ids).shape)",
    "```",
  )),
  "demo-regression": demoPage(demoLearningBookNavigation[3], markdown(
    "## 线性回归",
    "线性回归用一组可学习参数拟合输入与目标之间的关系，是理解训练循环的好起点。",
    "",
    "### 一次前向计算",
    "```python",
    "import torch",
    "",
    "weight = torch.tensor([[2.0]])",
    "bias = torch.tensor([1.0])",
    "features = torch.tensor([[3.0]])",
    "print(features @ weight + bias)",
    "```",
  )),
  "demo-softmax": demoPage(demoLearningBookNavigation[4], markdown(
    "## softmax 分类",
    "softmax 将模型输出的 logits 转换为各类别的概率分布，所有类别概率之和为 1。",
    "",
    "### 查看概率",
    "```python",
    "import torch",
    "",
    "logits = torch.tensor([[1.0, 2.0, 0.5]])",
    "probabilities = torch.softmax(logits, dim=-1)",
    "print(probabilities)",
    "```",
  )),
  "demo-cross-entropy": demoPage(demoLearningBookNavigation[5], markdown(
    "## 交叉熵损失",
    "交叉熵同时衡量分类概率与真实标签之间的差异。训练时通常直接把 logits 交给损失函数。",
    "",
    "### 计算一个损失值",
    "```python",
    "import torch",
    "",
    "logits = torch.tensor([[2.0, 0.5]])",
    "target = torch.tensor([0])",
    "loss = torch.nn.functional.cross_entropy(logits, target)",
    "print(loss.item())",
    "```",
  )),
  "demo-mlp": demoPage(demoLearningBookNavigation[6], markdown(
    "## 多层感知机",
    "多层感知机通过线性层和非线性激活函数组合出更强的表达能力。",
    "",
    "### 组装一个网络",
    "```python",
    "import torch",
    "from torch import nn",
    "",
    "model = nn.Sequential(nn.Linear(4, 8), nn.ReLU(), nn.Linear(8, 2))",
    "print(model(torch.randn(3, 4)).shape)",
    "```",
  )),
  "demo-dropout": demoPage(demoLearningBookNavigation[7], markdown(
    "## Dropout 正则化",
    "Dropout 在训练时随机关闭部分神经元，减少模型对个别特征的依赖。评估时要切换到 `eval` 模式。",
    "",
    "```python",
    "from torch import nn",
    "",
    "dropout = nn.Dropout(p=0.2)",
    "print(dropout.training)",
    "```",
  )),
  "demo-attention": demoPage(demoLearningBookNavigation[8], markdown(
    "## 注意力机制",
    "注意力机制让模型根据当前查询，为不同位置的键和值分配不同权重。",
    "",
    "### 先观察张量形状",
    "```python",
    "import torch",
    "",
    "query = torch.randn(2, 4, 8)",
    "key = torch.randn(2, 4, 8)",
    "scores = query @ key.transpose(-2, -1)",
    "print(scores.shape)",
    "```",
  )),
};
