"""LLM-powered conversation topic summarization.

Replaces the frontend's first-message truncation with a short (<=15 char)
topic line generated by the cheap ``utility`` model once a conversation has a
completed turn.

Design notes
------------
* **Single anchor message.**  Following the GPT/Gemini convention, the prompt
  uses only whoever spoke first (the opening user question, or the assistant's
  first message when the turn is assistant-initiated).  Later turns never
  change the topic, so a title is generated once and never recomputed.
* **Manual titles win.**  A manual rename sets ``title_is_manual``; the
  summarizer refuses to write over it.
* **Lease-fenced.**  Before calling the LLM a worker takes a short lease
  (``summary_lease_expires_at``) with a conditional UPDATE, so two workers that
  both observed an unsummarised session do not pay for the same LLM call.
* **Durable via sweep.**  The fire-and-forget ``schedule_summary`` is a fast
  path; a periodic ``summary_sweep_loop`` backfills anything that was lost to a
  restart, container rebuild or event-loop failure.
"""

from __future__ import annotations

import asyncio
from datetime import datetime, timedelta, timezone
from typing import Any

from langchain_core.messages import HumanMessage
from sqlalchemy import exists, or_, select, text
from sqlalchemy.ext.asyncio import AsyncSession, async_sessionmaker

from core.prompt_runtime.manager import global_prompt_runtime
from server.agent.llm_factory import get_utility_llm
from server.infrastructure.mysql.models import ConversationModel, TurnModel
from server.session.title_text import (
    clean_title,
    normalize_whitespace,
    strip_learning_preamble,
    strip_markdown_noise,
)
from utils.logger import get_logger

logger = get_logger("shiliu.session_summary")

MAX_TITLE_CHARS = 15
MAX_OUTPUT_TOKENS = 40
# Bound the prompt: a single turn can still contain a very long answer, tool
# output or attachment dump.
MAX_INPUT_CHARS = 2_000

# How long a worker keeps the summary lease before another may retry.
SUMMARY_LEASE_S = 60
# Sweep batch size / cadence for the durable backfill.
SWEEP_BATCH = 25
SWEEP_INTERVAL_S = 5
# Retry budget for the first summary.  On LLM failure the lease is extended
# (exponential backoff) rather than cleared, so an unavailable model cannot
# trigger a retry storm across the 5-second sweep cadence.
BASE_BACKOFF_S = 60
MAX_BACKOFF_S = 3600
MAX_SUMMARY_ATTEMPTS = 10


def _utcnow() -> datetime:
    return datetime.now(timezone.utc).replace(tzinfo=None)


def _clean_input(text: str) -> str:
    return normalize_whitespace(strip_learning_preamble(text))


def _clean_result(text: str) -> str:
    # ``result_text`` is already free of tool JSON / thinking (those live in
    # transcripts), but drop any residual markers and light markdown noise.
    return normalize_whitespace(strip_markdown_noise(text))


def _clean_title(title: str) -> str:
    return clean_title(title, max_chars=MAX_TITLE_CHARS) or ""


def _truncate(text: str) -> str:
    return text[:MAX_INPUT_CHARS] if len(text) > MAX_INPUT_CHARS else text


def _select_turns(turns: list[TurnModel]) -> list[TurnModel]:
    """Return the single anchor turn (whoever spoke first), if any."""
    for turn in turns:
        if _clean_input(turn.input_text) or _clean_result(turn.result_text or ""):
            return [turn]
    return []


def _render_turns(turns: list[TurnModel]) -> str:
    """Render the anchor turn's opening message, bounded to ``MAX_INPUT_CHARS``."""
    for turn in turns:
        user = _clean_input(turn.input_text)
        if user:
            return f"[user]: {_truncate(user)}"
        assistant = _clean_result(turn.result_text or "")
        if assistant:
            return f"[assistant]: {_truncate(assistant)}"
    return ""


def _decide(
    turns: list[TurnModel],
    title_updated_at: datetime | None,
    title_is_manual: bool,
) -> datetime | None:
    """Return the summary basis (newest completed turn) if generation is due.

    A title is generated exactly once: only while no summary has been written
    yet (``title_updated_at IS NULL``) and the user has not renamed the session
    by hand.  The anchor message is fixed, so there is nothing to recompute.
    """
    if title_is_manual or title_updated_at is not None:
        return None
    return max(
        (t.completed_at for t in turns if t.completed_at is not None), default=None
    )


async def _load_state(
    session: AsyncSession, session_id: str
) -> tuple[datetime | None, bool, list[TurnModel], int]:
    row = (
        await session.execute(
            select(
                ConversationModel.title_updated_at,
                ConversationModel.title_is_manual,
                ConversationModel.summary_attempts,
            ).where(ConversationModel.id == session_id)
        )
    ).one_or_none()
    title_updated_at = row.title_updated_at if row is not None else None
    title_is_manual = bool(row.title_is_manual) if row is not None else False
    summary_attempts = int(row.summary_attempts or 0) if row is not None else 0
    turns = list(
        (
            await session.execute(
                select(TurnModel)
                .where(
                    TurnModel.conversation_id == session_id,
                    TurnModel.status == "completed",
                )
                .order_by(TurnModel.created_at, TurnModel.id)
            )
        ).scalars().all()
    )
    return title_updated_at, title_is_manual, turns, summary_attempts


async def _generate_title(text: str, llm: Any) -> str | None:
    prompt = global_prompt_runtime.render("session.summary", conversation=text)
    response = await llm.ainvoke(
        [HumanMessage(content=prompt)], max_tokens=MAX_OUTPUT_TOKENS
    )
    return _clean_title(str(getattr(response, "content", "") or "")) or None


async def _claim_summary(
    session: AsyncSession, session_id: str, *, now: datetime, lease_s: int
) -> bool:
    """Atomically take the summary lease, re-validating the due conditions."""
    result = await session.execute(
        text(
            "UPDATE nlp_conversations "
            "SET summary_lease_expires_at=:lease_until "
            "WHERE id=:id AND status='active' AND title_is_manual=0 "
            "AND title_updated_at IS NULL "
            "AND (summary_lease_expires_at IS NULL OR summary_lease_expires_at < :now)"
        ),
        {
            "id": session_id,
            "lease_until": now + timedelta(seconds=lease_s),
            "now": now,
        },
    )
    return result.rowcount == 1


async def _backoff_summary(
    session: AsyncSession,
    session_id: str,
    *,
    now: datetime,
    attempts_so_far: int,
) -> None:
    """Park the lease in the future and bump the attempt counter.

    Instead of clearing the lease on LLM failure (which would let the next
    5-second sweep immediately retry the same doomed batch), we extend the
    lease with exponential backoff so the sweep naturally skips the session
    until the model is likely available again.  ``attempts_so_far`` is the
    value observed *before* this call; it drives the backoff duration and the
    row-level counter is incremented atomically in the same UPDATE.
    """
    backoff = min(BASE_BACKOFF_S * (2 ** max(attempts_so_far, 0)), MAX_BACKOFF_S)
    await session.execute(
        text(
            "UPDATE nlp_conversations "
            "SET summary_lease_expires_at=:until, "
            "summary_attempts=summary_attempts+1 "
            "WHERE id=:id"
        ),
        {"id": session_id, "until": now + timedelta(seconds=backoff)},
    )


async def _write_title(
    session: AsyncSession, session_id: str, title: str, basis: datetime
) -> bool:
    """Store the title once, releasing the lease; manual/raced writes lose."""
    result = await session.execute(
        text(
            "UPDATE nlp_conversations "
            "SET title=:title, title_updated_at=:basis, "
            "summary_lease_expires_at=NULL, summary_attempts=0 "
            "WHERE id=:id AND title_is_manual=0 AND title_updated_at IS NULL"
        ),
        {"title": title, "basis": basis, "id": session_id},
    )
    return result.rowcount == 1


async def build_conversation_text(
    session_id: str, session_factory: async_sessionmaker[AsyncSession]
) -> str:
    """Render the anchor turn of a session as prompt text."""
    async with session_factory() as session:
        _title_updated_at, _title_is_manual, turns, _summary_attempts = (
            await _load_state(session, session_id)
        )
    return _render_turns(_select_turns(turns))


async def generate_and_store_summary(
    session_id: str, session_factory: async_sessionmaker[AsyncSession]
) -> bool:
    """Generate a topic title and conditionally store it.  Never raises."""
    try:
        async with session_factory() as session:
            title_updated_at, title_is_manual, turns, summary_attempts = (
                await _load_state(session, session_id)
            )
        basis = _decide(turns, title_updated_at, title_is_manual)
        if basis is None:
            return False
        text = _render_turns(_select_turns(turns))
        if not text:
            return False
        if summary_attempts >= MAX_SUMMARY_ATTEMPTS:
            # Exhausted the retry budget; leave the row alone until a manual
            # rename or a future migration resets it.  Logging at info level
            # keeps the operator aware without screaming into error channels.
            logger.info(
                "session summary gave up after %s attempts",
                summary_attempts,
                extra={"session_id": session_id},
            )
            return False

        now = _utcnow()
        async with session_factory.begin() as session:
            if not await _claim_summary(
                session, session_id, now=now, lease_s=SUMMARY_LEASE_S
            ):
                return False

        title: str | None = None
        try:
            title = await _generate_title(text, get_utility_llm())
        except asyncio.CancelledError:
            # Worker is shutting down; leave the 60s claim in place so another
            # worker can pick it up after the lease expires naturally.
            raise
        except Exception:
            logger.exception(
                "session summary LLM call failed", session_id=session_id
            )

        if title is None:
            now = _utcnow()
            async with session_factory.begin() as session:
                await _backoff_summary(
                    session,
                    session_id,
                    now=now,
                    attempts_so_far=summary_attempts,
                )
            return False

        async with session_factory.begin() as session:
            return await _write_title(session, session_id, title, basis)
    except asyncio.CancelledError:
        raise
    except Exception:
        logger.exception("session summary generation failed", session_id=session_id)
        return False


async def _find_due_sessions(
    session: AsyncSession, *, now: datetime, batch: int
) -> list[str]:
    """Return conversation ids that are due for a first summary."""
    return list(
        (
            await session.scalars(
                select(ConversationModel.id)
                .where(
                    ConversationModel.status == "active",
                    ConversationModel.title_is_manual.is_(False),
                    ConversationModel.title_updated_at.is_(None),
                    ConversationModel.summary_attempts < MAX_SUMMARY_ATTEMPTS,
                    or_(
                        ConversationModel.summary_lease_expires_at.is_(None),
                        ConversationModel.summary_lease_expires_at < now,
                    ),
                    exists().where(
                        TurnModel.conversation_id == ConversationModel.id,
                        TurnModel.status == "completed",
                    ),
                )
                .order_by(ConversationModel.created_at, ConversationModel.id)
                .limit(batch)
            )
        ).all()
    )


async def sweep_summaries(
    session_factory: async_sessionmaker[AsyncSession], *, batch: int = SWEEP_BATCH
) -> int:
    """Backfill one batch of conversations that missed their summary."""
    now = _utcnow()
    async with session_factory() as session:
        ids = await _find_due_sessions(session, now=now, batch=batch)
    processed = 0
    for session_id in ids:
        if await generate_and_store_summary(session_id, session_factory):
            processed += 1
    return processed


async def summary_sweep_loop(
    session_factory: async_sessionmaker[AsyncSession],
    *,
    interval_s: int = SWEEP_INTERVAL_S,
    batch: int = SWEEP_BATCH,
) -> None:
    """Run the durable backfill forever; survives restarts and races."""
    while True:
        try:
            await sweep_summaries(session_factory, batch=batch)
        except asyncio.CancelledError:
            raise
        except Exception:
            logger.exception("session summary sweep pass failed")
        await asyncio.sleep(interval_s)


_background_tasks: set[asyncio.Task[Any]] = set()


def schedule_summary(
    session_factory: async_sessionmaker[AsyncSession], session_id: str
) -> None:
    """Fire-and-forget summary scheduling; safe to call from any async context."""
    task = asyncio.create_task(
        generate_and_store_summary(session_id, session_factory),
        name=f"session-summary:{session_id}",
    )
    # Hold a strong reference so the task is not garbage-collected while
    # suspended on the LLM await; discard it once it finishes.
    _background_tasks.add(task)
    task.add_done_callback(_background_tasks.discard)
