"""LLM-powered conversation topic summarization.

Replaces the frontend's first-message truncation with a short (<=15 char)
topic line generated by the cheap ``utility`` model once a conversation has a
completed turn.

Design notes
------------
* **Whole dialogue, recomputed per turn.**  The prompt renders the opening turn
  plus as many of the newest turns as fit in ``MAX_INPUT_CHARS``, so the title
  summarises what the conversation actually covered -- both sides of the
  exchange -- instead of only the user's opening question.  Generation re-arms
  whenever a completed turn is newer than the standing ``title_updated_at``; an
  unchanged dialogue is never re-summarised, so a settled conversation costs
  nothing.
* **Manual titles win.**  A manual rename sets ``title_is_manual``; the
  summarizer refuses to write over it.
* **Lease-fenced.**  Before calling the LLM a worker takes a short lease
  (``summary_lease_expires_at``) with a conditional UPDATE, so two workers that
  both observed the same due basis do not pay for the same LLM call.
* **Basis-fenced writes.**  Both the claim and the title write require the
  stored basis to be older than the one being written, so a worker overtaken by
  a newer turn cannot roll the title back.
* **Durable via sweep.**  The fire-and-forget ``schedule_summary`` is a fast
  path; a periodic ``summary_sweep_loop`` backfills anything that was lost to a
  restart, container rebuild or event-loop failure.
"""

from __future__ import annotations

import asyncio
from dataclasses import dataclass
from datetime import datetime, timedelta, timezone
from typing import Any

from langchain_core.messages import HumanMessage
from sqlalchemy import exists, or_, select, text
from sqlalchemy.ext.asyncio import AsyncSession, async_sessionmaker

from core.model_runtime.usage import UsageAttributionContext, bind_usage_attribution
from core.prompt_runtime.manager import global_prompt_runtime
from server.agent.llm_factory import get_utility_llm
from server.infrastructure.mysql.models import ConversationModel, TurnModel
from server.session.title_text import (
    clean_title,
    normalize_whitespace,
    strip_learning_preamble,
    strip_markdown_noise,
)
from utils.logger import get_logger

logger = get_logger("shiliu.session_summary")

MAX_TITLE_CHARS = 15
MAX_OUTPUT_TOKENS = 40
# Bound the prompt: a single turn can still contain a very long answer, tool
# output or attachment dump.
MAX_INPUT_CHARS = 2_000
# Per-message cap so one huge reply cannot crowd every other turn out of the
# budget.  Two capped messages plus their role prefixes stay well under
# MAX_INPUT_CHARS, so the newest turn always survives intact.
MAX_MESSAGE_CHARS = 500

# How long a worker keeps the summary lease before another may retry.
SUMMARY_LEASE_S = 60
# Sweep batch size / cadence for the durable backfill.
SWEEP_BATCH = 25
SWEEP_INTERVAL_S = 5
# Retry budget for one title generation.  On LLM failure the lease is extended
# (exponential backoff) rather than cleared, so an unavailable model cannot
# trigger a retry storm across the 5-second sweep cadence.  A successful write
# resets the counter, so the next turn's regeneration gets a fresh budget.
BASE_BACKOFF_S = 60
MAX_BACKOFF_S = 3600
MAX_SUMMARY_ATTEMPTS = 10


@dataclass(frozen=True, slots=True)
class _SummaryState:
    title_updated_at: datetime | None
    title_is_manual: bool
    turns: list[TurnModel]
    summary_attempts: int
    workspace_id: str | None
    owner_user_id: str | None


def _utcnow() -> datetime:
    return datetime.now(timezone.utc).replace(tzinfo=None)


def _clean_input(text: str) -> str:
    return normalize_whitespace(strip_learning_preamble(text))


def _clean_result(text: str) -> str:
    # ``result_text`` is already free of tool JSON / thinking (those live in
    # transcripts), but drop any residual markers and light markdown noise.
    return normalize_whitespace(strip_markdown_noise(text))


def _clean_title(title: str) -> str:
    return clean_title(title, max_chars=MAX_TITLE_CHARS) or ""


def _truncate(text: str, limit: int = MAX_INPUT_CHARS) -> str:
    return text[:limit] if len(text) > limit else text


def _select_turns(turns: list[TurnModel]) -> list[TurnModel]:
    """Return every turn that contributes readable dialogue, oldest first."""
    return [
        turn
        for turn in turns
        if _clean_input(turn.input_text) or _clean_result(turn.result_text or "")
    ]


def _turn_lines(turn: TurnModel) -> list[str]:
    """Render one turn as ``[user]:`` / ``[assistant]:`` prompt lines."""
    lines: list[str] = []
    user = _clean_input(turn.input_text)
    if user:
        lines.append(f"[user]: {_truncate(user, MAX_MESSAGE_CHARS)}")
    assistant = _clean_result(turn.result_text or "")
    if assistant:
        lines.append(f"[assistant]: {_truncate(assistant, MAX_MESSAGE_CHARS)}")
    return lines


def _render_turns(turns: list[TurnModel]) -> str:
    """Render the dialogue within ``MAX_INPUT_CHARS``, in chronological order.

    The opening turn is always kept because it anchors the topic; the remaining
    budget is filled newest-first so the title also reflects where the
    conversation has got to.  A turn is added whole (question before answer) or
    not at all, so the rendering never ends mid-exchange.
    """
    rendered = [lines for lines in (_turn_lines(turn) for turn in turns) if lines]
    if not rendered:
        return ""
    anchor = rendered[0]
    used = sum(len(line) + 1 for line in anchor)
    tail: list[str] = []
    for lines in reversed(rendered[1:]):
        cost = sum(len(line) + 1 for line in lines)
        if used + cost > MAX_INPUT_CHARS:
            break
        tail = lines + tail
        used += cost
    return _truncate("\n".join(anchor + tail))


def _decide(
    turns: list[TurnModel],
    title_updated_at: datetime | None,
    title_is_manual: bool,
) -> datetime | None:
    """Return the summary basis (newest completed turn) if generation is due.

    Generation is due while the user has not renamed the session by hand and the
    dialogue has advanced past whatever the standing title was built from, so
    every newly completed turn re-titles the session while an unchanged dialogue
    is left alone.
    """
    if title_is_manual:
        return None
    basis = max(
        (t.completed_at for t in turns if t.completed_at is not None), default=None
    )
    if basis is None:
        return None
    if title_updated_at is not None and basis <= title_updated_at:
        return None
    return basis


async def _load_state(
    session: AsyncSession, session_id: str
) -> _SummaryState:
    row = (
        await session.execute(
            select(
                ConversationModel.title_updated_at,
                ConversationModel.title_is_manual,
                ConversationModel.summary_attempts,
                ConversationModel.workspace_id,
                ConversationModel.owner_user_id,
            ).where(ConversationModel.id == session_id)
        )
    ).one_or_none()
    title_updated_at = row.title_updated_at if row is not None else None
    title_is_manual = bool(row.title_is_manual) if row is not None else False
    summary_attempts = int(row.summary_attempts or 0) if row is not None else 0
    workspace_id = (
        str(row.workspace_id) if row is not None and row.workspace_id else None
    )
    owner_user_id = (
        str(row.owner_user_id) if row is not None and row.owner_user_id else None
    )
    turns = list(
        (
            await session.execute(
                select(TurnModel)
                .where(
                    TurnModel.conversation_id == session_id,
                    TurnModel.status == "completed",
                )
                .order_by(TurnModel.created_at, TurnModel.id)
            )
        ).scalars().all()
    )
    return _SummaryState(
        title_updated_at=title_updated_at,
        title_is_manual=title_is_manual,
        turns=turns,
        summary_attempts=summary_attempts,
        workspace_id=workspace_id,
        owner_user_id=owner_user_id,
    )


async def _generate_title(text: str, llm: Any) -> str | None:
    prompt = global_prompt_runtime.render("session.summary", conversation=text)
    response = await llm.ainvoke(
        [HumanMessage(content=prompt)], max_tokens=MAX_OUTPUT_TOKENS
    )
    return _clean_title(str(getattr(response, "content", "") or "")) or None


async def _claim_summary(
    session: AsyncSession,
    session_id: str,
    *,
    now: datetime,
    lease_s: int,
    basis: datetime,
) -> bool:
    """Atomically take the summary lease for one basis.

    The basis fence (``title_updated_at < :basis``) replaces the old write-once
    ``title_updated_at IS NULL`` gate: a session is re-titled as its dialogue
    grows, but never for a basis another worker has already covered.
    """
    result = await session.execute(
        text(
            "UPDATE nlp_conversations "
            "SET summary_lease_expires_at=:lease_until "
            "WHERE id=:id AND status='active' AND title_is_manual=0 "
            "AND (title_updated_at IS NULL OR title_updated_at < :basis) "
            "AND (summary_lease_expires_at IS NULL OR summary_lease_expires_at < :now)"
        ),
        {
            "id": session_id,
            "lease_until": now + timedelta(seconds=lease_s),
            "now": now,
            "basis": basis,
        },
    )
    return result.rowcount == 1


async def _backoff_summary(
    session: AsyncSession,
    session_id: str,
    *,
    now: datetime,
    attempts_so_far: int,
) -> None:
    """Park the lease in the future and bump the attempt counter.

    Instead of clearing the lease on LLM failure (which would let the next
    5-second sweep immediately retry the same doomed batch), we extend the
    lease with exponential backoff so the sweep naturally skips the session
    until the model is likely available again.  ``attempts_so_far`` is the
    value observed *before* this call; it drives the backoff duration and the
    row-level counter is incremented atomically in the same UPDATE.
    """
    backoff = min(BASE_BACKOFF_S * (2 ** max(attempts_so_far, 0)), MAX_BACKOFF_S)
    await session.execute(
        text(
            "UPDATE nlp_conversations "
            "SET summary_lease_expires_at=:until, "
            "summary_attempts=summary_attempts+1 "
            "WHERE id=:id"
        ),
        {"id": session_id, "until": now + timedelta(seconds=backoff)},
    )


async def _write_title(
    session: AsyncSession, session_id: str, title: str, basis: datetime
) -> bool:
    """Store the title for one basis, releasing the lease.

    Manual renames always win, and a basis that is no longer newer than the
    stored one loses -- so a worker overtaken by a newer turn cannot roll the
    title back.
    """
    result = await session.execute(
        text(
            "UPDATE nlp_conversations "
            "SET title=:title, title_updated_at=:basis, "
            "summary_lease_expires_at=NULL, summary_attempts=0 "
            "WHERE id=:id AND title_is_manual=0 "
            "AND (title_updated_at IS NULL OR title_updated_at < :basis)"
        ),
        {"title": title, "basis": basis, "id": session_id},
    )
    return result.rowcount == 1


async def build_conversation_text(
    session_id: str, session_factory: async_sessionmaker[AsyncSession]
) -> str:
    """Render a session's dialogue as prompt text."""
    async with session_factory() as session:
        state = await _load_state(session, session_id)
    return _render_turns(_select_turns(state.turns))


async def generate_and_store_summary(
    session_id: str, session_factory: async_sessionmaker[AsyncSession]
) -> bool:
    """Generate a topic title and conditionally store it.  Never raises."""
    try:
        async with session_factory() as session:
            state = await _load_state(session, session_id)
        basis = _decide(
            state.turns,
            state.title_updated_at,
            state.title_is_manual,
        )
        if basis is None:
            return False
        text = _render_turns(_select_turns(state.turns))
        if not text:
            return False
        if state.summary_attempts >= MAX_SUMMARY_ATTEMPTS:
            # Exhausted the retry budget; leave the row alone until a manual
            # rename or a future migration resets it.  Logging at info level
            # keeps the operator aware without screaming into error channels.
            logger.info(
                "session summary gave up after %s attempts",
                state.summary_attempts,
                extra={"session_id": session_id},
            )
            return False
        now = _utcnow()
        async with session_factory.begin() as session:
            if not await _claim_summary(
                session, session_id, now=now, lease_s=SUMMARY_LEASE_S, basis=basis
            ):
                return False

        if not state.owner_user_id or not state.workspace_id:
            logger.error(
                "session summary is missing usage attribution identity",
                session_id=session_id,
            )
            async with session_factory.begin() as session:
                await _backoff_summary(
                    session,
                    session_id,
                    now=_utcnow(),
                    attempts_so_far=state.summary_attempts,
                )
            return False

        title: str | None = None
        try:
            attribution = UsageAttributionContext(
                request_id=(
                    f"session-summary:{session_id}:{state.summary_attempts + 1}"
                ),
                user_id=state.owner_user_id,
                workspace_id=state.workspace_id,
                conversation_id=session_id,
                turn_id=None,
                purpose="other",
            )
            with bind_usage_attribution(attribution):
                title = await _generate_title(text, get_utility_llm())
        except asyncio.CancelledError:
            # Worker is shutting down; leave the 60s claim in place so another
            # worker can pick it up after the lease expires naturally.
            raise
        except Exception:
            logger.exception(
                "session summary LLM call failed", session_id=session_id
            )

        if title is None:
            now = _utcnow()
            async with session_factory.begin() as session:
                await _backoff_summary(
                    session,
                    session_id,
                    now=now,
                    attempts_so_far=state.summary_attempts,
                )
            return False

        async with session_factory.begin() as session:
            return await _write_title(session, session_id, title, basis)
    except asyncio.CancelledError:
        raise
    except Exception:
        logger.exception("session summary generation failed", session_id=session_id)
        return False


async def _find_due_sessions(
    session: AsyncSession, *, now: datetime, batch: int
) -> list[str]:
    """Return conversation ids whose dialogue advanced past their title.

    A session is due when some completed turn is newer than the basis the
    standing title was built from (or no title has been written yet).  The batch
    is ordered by most recent activity so that, under the per-turn cadence, the
    conversations a user is looking at get retitled first.
    """
    newer_turn = exists().where(
        TurnModel.conversation_id == ConversationModel.id,
        TurnModel.status == "completed",
        TurnModel.completed_at.isnot(None),
        or_(
            ConversationModel.title_updated_at.is_(None),
            TurnModel.completed_at > ConversationModel.title_updated_at,
        ),
    )
    return list(
        (
            await session.scalars(
                select(ConversationModel.id)
                .where(
                    ConversationModel.status == "active",
                    ConversationModel.title_is_manual.is_(False),
                    ConversationModel.summary_attempts < MAX_SUMMARY_ATTEMPTS,
                    or_(
                        ConversationModel.summary_lease_expires_at.is_(None),
                        ConversationModel.summary_lease_expires_at < now,
                    ),
                    newer_turn,
                )
                .order_by(
                    ConversationModel.last_message_at.desc(),
                    ConversationModel.id,
                )
                .limit(batch)
            )
        ).all()
    )


async def sweep_summaries(
    session_factory: async_sessionmaker[AsyncSession], *, batch: int = SWEEP_BATCH
) -> int:
    """Backfill one batch of conversations that missed their summary."""
    now = _utcnow()
    async with session_factory() as session:
        ids = await _find_due_sessions(session, now=now, batch=batch)
    processed = 0
    for session_id in ids:
        if await generate_and_store_summary(session_id, session_factory):
            processed += 1
    return processed


async def summary_sweep_loop(
    session_factory: async_sessionmaker[AsyncSession],
    *,
    interval_s: int = SWEEP_INTERVAL_S,
    batch: int = SWEEP_BATCH,
) -> None:
    """Run the durable backfill forever; survives restarts and races."""
    while True:
        try:
            await sweep_summaries(session_factory, batch=batch)
        except asyncio.CancelledError:
            raise
        except Exception:
            logger.exception("session summary sweep pass failed")
        await asyncio.sleep(interval_s)


_background_tasks: set[asyncio.Task[Any]] = set()


def schedule_summary(
    session_factory: async_sessionmaker[AsyncSession], session_id: str
) -> None:
    """Fire-and-forget summary scheduling; safe to call from any async context."""
    task = asyncio.create_task(
        generate_and_store_summary(session_id, session_factory),
        name=f"session-summary:{session_id}",
    )
    # Hold a strong reference so the task is not garbage-collected while
    # suspended on the LLM await; discard it once it finishes.
    _background_tasks.add(task)
    task.add_done_callback(_background_tasks.discard)
