import { BookOpen, FilePlus2, Plus, Power, Trash2 } from "lucide-react";
import { useState } from "react";

import { ConfirmDialog } from "@/shared/ui/ConfirmDialog";
import type { CourseTopic, ExerciseBlueprint, GuidedBlueprint, KnowledgePoint, ReviewBlueprint, RubricPoint } from "@/shared/types";
import { createUuid } from "@/shared/utils/uuid";

const makeId = (kind: string) => `${kind}_${createUuid().replaceAll("-", "").slice(0, 12)}`;
const statusText = (status: "draft" | "enabled" | "disabled") => status === "enabled" ? "已启用" : status === "disabled" ? "已停用" : "草稿";

function RemoveButton({ label, onRemove }: { label: string; onRemove: () => void }) {
  const [open, setOpen] = useState(false);
  return <><button className="teacher-danger-button" type="button" onClick={() => setOpen(true)}><Trash2 size={15} />删除</button><ConfirmDialog open={open} title={`删除${label}？`} description="该项将从当前教学目录移除；既有学习记录和蓝图快照不会受影响。" onClose={() => setOpen(false)} onConfirm={() => { onRemove(); setOpen(false); }} /></>;
}

function StatusButton({ status, onChange }: { status: "draft" | "enabled" | "disabled"; onChange: (status: "enabled" | "disabled") => void }) {
  return <button className={status === "enabled" ? "teacher-status-button enabled" : "teacher-status-button"} type="button" onClick={() => onChange(status === "enabled" ? "disabled" : "enabled")}><Power size={14} />{status === "enabled" ? "停用" : "启用"}</button>;
}

function StatusBadge({ status }: { status: "draft" | "enabled" | "disabled" }) { return <span className={`teacher-status-badge ${status}`}>{statusText(status)}</span>; }

function KnowledgePointEditor({ point, onChange, onRemove }: { point: KnowledgePoint; onChange: (point: KnowledgePoint) => void; onRemove: () => void }) {
  const [expanded, setExpanded] = useState(false);
  return <article className={`teacher-nested-card ${expanded ? "is-expanded" : ""}`}>
    <div className="teacher-card-heading"><button className="teacher-card-toggle" type="button" aria-label={`${point.name || "知识点"} ${expanded ? "收起" : "展开"}`} aria-expanded={expanded} onClick={() => setExpanded(!expanded)}><BookOpen size={15} /><strong>{point.name || "未命名知识点"}</strong><StatusBadge status={point.status} /></button><div className="teacher-card-actions"><StatusButton status={point.status} onChange={(status) => onChange({ ...point, status })} /><RemoveButton label={`知识点“${point.name || "未命名"}”`} onRemove={onRemove} /></div></div>
    {expanded && <div className="teacher-editor-grid">
      <label>知识点名称<input value={point.name} onChange={(event) => onChange({ ...point, name: event.target.value })} placeholder="例如：缩放点积注意力" /></label>
      <label>知识点 Markdown<textarea rows={6} value={point.markdown} onChange={(event) => onChange({ ...point, markdown: event.target.value })} placeholder="用 Markdown 写清概念边界、必须覆盖的内容与容易混淆处。" /></label>
      <p className="teacher-field-hint">启用的知识点会成为该主题的回答范围约束；可使用公式、表格、代码和 Mermaid。</p>
    </div>}
  </article>;
}

export function TopicCatalogEditor({ topics, onChange }: { topics: CourseTopic[]; onChange: (topics: CourseTopic[]) => void }) {
  const [name, setName] = useState("");
  const [description, setDescription] = useState("");
  const create = () => { if (!name.trim()) return; onChange([...topics, { id: makeId("topic"), name: name.trim(), description: description.trim(), status: "enabled", knowledge_points: [] }]); setName(""); setDescription(""); };
  const update = (topic: CourseTopic) => onChange(topics.map((item) => item.id === topic.id ? topic : item));
  return <div className="teacher-stack">
    <section className="teacher-panel teacher-create-card"><header><div><span className="teacher-eyebrow">课程导航</span><h2>{topics.length ? "新建主题" : "创建第一个主题"}</h2><p>主题、知识点和蓝图均由教师手动创建并保存；不会导入预置课程数据。</p></div></header><div className="teacher-editor-grid"><label>主题名称<input aria-label="主题名称" value={name} onChange={(event) => setName(event.target.value)} placeholder="例如：Transformer" /></label><label>主题说明<textarea aria-label="主题说明" value={description} onChange={(event) => setDescription(event.target.value)} placeholder="说明该主题的学习范围" /></label><button className="teacher-primary-button" type="button" disabled={!name.trim()} onClick={create}><Plus size={16} />创建主题</button></div></section>
    <section className="teacher-panel"><header><div><h2>主题目录</h2><p>共 {topics.length} 个主题。编辑后点击页面底部的“保存教学目录”写入后端。</p></div></header>{topics.length ? <div className="teacher-catalog-list">{topics.map((topic) => <TopicCard key={topic.id} topic={topic} onChange={update} onRemove={() => onChange(topics.filter((item) => item.id !== topic.id))} />)}</div> : <Empty text="还没有主题。请先创建一个课程主题，再添加知识点。" />}</section>
  </div>;
}

function TopicCard({ topic, onChange, onRemove }: { topic: CourseTopic; onChange: (topic: CourseTopic) => void; onRemove: () => void }) {
  const [expanded, setExpanded] = useState(false);
  const setPoints = (knowledge_points: KnowledgePoint[]) => onChange({ ...topic, knowledge_points });
  return <article className={`teacher-catalog-card teacher-topic-card ${expanded ? "is-expanded" : ""}`}><div className="teacher-card-heading"><button className="teacher-card-toggle" type="button" aria-label={`${topic.name || "主题"} ${expanded ? "收起" : "展开"}`} aria-expanded={expanded} onClick={() => setExpanded(!expanded)}><BookOpen size={17} /><strong>{topic.name || "未命名主题"}</strong><StatusBadge status={topic.status} /><span className="teacher-item-count">{topic.knowledge_points.length} 个知识点</span></button><div className="teacher-card-actions"><StatusButton status={topic.status} onChange={(status) => onChange({ ...topic, status })} /><RemoveButton label={`主题“${topic.name || "未命名"}”`} onRemove={onRemove} /></div></div>{expanded && <div className="teacher-editor-grid"><label>主题名称<input value={topic.name} onChange={(event) => onChange({ ...topic, name: event.target.value })} /></label><label>主题说明<textarea rows={3} value={topic.description} onChange={(event) => onChange({ ...topic, description: event.target.value })} /></label><div className="teacher-subsection-heading"><div><h3>知识点</h3><p>Markdown 内容会约束模型在该主题下的回答范围。</p></div><button className="teacher-secondary-button" type="button" onClick={() => setPoints([...topic.knowledge_points, { id: makeId("kp"), name: "新知识点", markdown: "", status: "enabled", sort_order: topic.knowledge_points.length }])}><Plus size={15} />添加知识点</button></div><div className="teacher-nested-list">{topic.knowledge_points.length ? topic.knowledge_points.map((point) => <KnowledgePointEditor key={point.id} point={point} onChange={(next) => setPoints(topic.knowledge_points.map((item) => item.id === next.id ? next : item))} onRemove={() => setPoints(topic.knowledge_points.filter((item) => item.id !== point.id))} />) : <Empty text="暂无知识点；添加后可填写 Markdown 教学边界。" compact />}</div></div>}</article>;
}

type Blueprint = ExerciseBlueprint | ReviewBlueprint;
type BlueprintKind = "exercise" | "review";
function blueprintName(kind: BlueprintKind) { return kind === "exercise" ? "出题蓝图" : "复习蓝图"; }

export function BlueprintCatalogEditor({ kind, topics, blueprints, exerciseBlueprints, onChange }: { kind: BlueprintKind; topics: CourseTopic[]; blueprints: Blueprint[]; exerciseBlueprints: ExerciseBlueprint[]; onChange: (items: Blueprint[]) => void }) {
  const [name, setName] = useState(""); const [topicId, setTopicId] = useState(""); const [pointId, setPointId] = useState(""); const [instructions, setInstructions] = useState(""); const [questionType, setQuestionType] = useState("简答");
  const topicOptions = topics.filter((topic) => topic.status !== "disabled");
  const selectedTopic = topicOptions.find((topic) => topic.id === topicId);
  const points = selectedTopic?.knowledge_points.filter((point) => point.status === "enabled") ?? [];
  const create = () => { if (!name.trim() || !topicId || !pointId || !instructions.trim() || !questionType.trim()) return; const base = { id: makeId(kind), name: name.trim(), topic_id: topicId, knowledge_point_id: pointId, instructions: instructions.trim(), question_type: questionType.trim(), rubric: [], status: "draft" as const }; const item: Blueprint = kind === "exercise" ? base : { ...base, exercise_blueprint_id: null }; onChange([...blueprints, item]); setName(""); setInstructions(""); setQuestionType("简答"); };
  return <div className="teacher-stack"><section className="teacher-panel teacher-create-card"><header><div><span className="teacher-eyebrow">单题蓝图</span><h2>创建{blueprintName(kind)}</h2><p>每张蓝图只生成一道题，必须绑定主题中的一个知识点；学生开始练习时后端会随机抽取一张有效蓝图。</p></div></header>{topicOptions.length ? <div className="teacher-editor-grid"><div className="teacher-editor-two-column"><label>{blueprintName(kind)}名称<input aria-label={`${kind}蓝图名称`} value={name} onChange={(event) => setName(event.target.value)} /></label><label>所属主题<select aria-label={`${kind}所属主题`} value={topicId} onChange={(event) => { setTopicId(event.target.value); setPointId(""); }}><option value="">选择主题</option>{topicOptions.map((topic) => <option value={topic.id} key={topic.id}>{topic.name}</option>)}</select></label></div><div className="teacher-editor-two-column"><label>关联知识点<select aria-label={`${kind}关联知识点`} value={pointId} disabled={!topicId} onChange={(event) => setPointId(event.target.value)}><option value="">选择一个知识点</option>{points.map((point) => <option value={point.id} key={point.id}>{point.name}</option>)}</select></label><label>题型<input aria-label={`${kind}题型`} value={questionType} onChange={(event) => setQuestionType(event.target.value)} placeholder="例如：简答" /></label></div><label>单题 Markdown 指令<textarea aria-label={`${kind}Markdown 指令`} rows={6} value={instructions} onChange={(event) => setInstructions(event.target.value)} placeholder="只描述这一道题的题干范围、数据要求与讲评规则。" /></label><button className="teacher-primary-button" type="button" disabled={!name.trim() || !topicId || !pointId || !instructions.trim() || !questionType.trim()} onClick={create}><FilePlus2 size={16} />创建单题草稿蓝图</button></div> : <Empty text="请先创建并启用一个主题和知识点，才能创建蓝图。" />}</section><section className="teacher-panel"><header><div><h2>{blueprintName(kind)}目录</h2><p>按主题与知识点组织；每张卡片对应一道题。</p></div></header>{topics.map((topic) => <section className="teacher-blueprint-topic" aria-label={`主题：${topic.name}`} key={topic.id}><header><span className="teacher-topic-marker">主题</span><h3>{topic.name}</h3><span className="teacher-topic-meta">{topic.knowledge_points.length} 个知识点</span></header>{topic.knowledge_points.map((point) => { const items = blueprints.filter((item) => item.topic_id === topic.id && item.knowledge_point_id === point.id); return <section className="teacher-blueprint-point" key={point.id}><header><div><span className="teacher-point-marker">知识点</span><strong>{point.name}</strong></div><span>{items.length} 张蓝图</span></header>{items.length ? <div className="teacher-catalog-list">{items.map((item) => <BlueprintCard key={item.id} kind={kind} item={item} topics={topics} exerciseBlueprints={exerciseBlueprints} onChange={(next) => onChange(blueprints.map((value) => value.id === next.id ? next : value))} onRemove={() => onChange(blueprints.filter((value) => value.id !== item.id))} />)}</div> : <Empty text="该知识点暂未配置蓝图。" compact />}</section>; })}</section>)}</section></div>;
}

function BlueprintCard({ kind, item, topics, exerciseBlueprints, onChange, onRemove }: { kind: BlueprintKind; item: Blueprint; topics: CourseTopic[]; exerciseBlueprints: ExerciseBlueprint[]; onChange: (item: Blueprint) => void; onRemove: () => void }) {
  const [expanded, setExpanded] = useState(false); const topic = topics.find((value) => value.id === item.topic_id); const allowedPoints = topic?.knowledge_points ?? [];
  const update = (patch: Partial<Blueprint>) => onChange({ ...item, ...patch } as Blueprint);
  const rubrics = item.rubric;
  return <article className={`teacher-catalog-card teacher-blueprint-card ${expanded ? "is-expanded" : ""}`}><div className="teacher-card-heading"><button className="teacher-card-toggle" type="button" aria-label={`${item.name || "蓝图"} ${expanded ? "收起" : "展开"}`} aria-expanded={expanded} onClick={() => setExpanded(!expanded)}><SparkleMark /><strong>{item.name || "未命名蓝图"}</strong><StatusBadge status={item.status} /></button><div className="teacher-card-actions"><StatusButton status={item.status} onChange={(status) => update({ status })} /><RemoveButton label={`${blueprintName(kind)}“${item.name || "未命名"}”`} onRemove={onRemove} /></div></div>{expanded && <div className="teacher-editor-grid"><div className="teacher-editor-two-column"><label>蓝图名称<input value={item.name} onChange={(event) => update({ name: event.target.value })} /></label><label>所属主题<select value={item.topic_id} onChange={(event) => update({ topic_id: event.target.value, knowledge_point_id: "" })}>{topics.map((value) => <option value={value.id} key={value.id}>{value.name}</option>)}</select></label></div><label>关联知识点<select value={item.knowledge_point_id} onChange={(event) => update({ knowledge_point_id: event.target.value })}>{allowedPoints.map((point) => <option value={point.id} key={point.id}>{point.name}</option>)}</select></label>{kind === "review" && <label>关联练习蓝图<select value={(item as ReviewBlueprint).exercise_blueprint_id ?? ""} onChange={(event) => update({ exercise_blueprint_id: event.target.value || null })}><option value="">不关联，使用自身指令</option>{exerciseBlueprints.filter((blueprint) => blueprint.topic_id === item.topic_id && blueprint.knowledge_point_id === item.knowledge_point_id).map((blueprint) => <option value={blueprint.id} key={blueprint.id}>{blueprint.name}</option>)}</select></label>}<label>题型<input value={item.question_type} onChange={(event) => update({ question_type: event.target.value })} /></label><label>单题 Markdown 指令<textarea rows={7} value={item.instructions} onChange={(event) => update({ instructions: event.target.value })} /></label><RubricEditor rubric={rubrics} onChange={(rubric) => update({ rubric })} /></div>}</article>;
}

function RubricEditor({ rubric, onChange }: { rubric: RubricPoint[]; onChange: (rubric: RubricPoint[]) => void }) { return <fieldset className="teacher-rubric"><legend>评分标准</legend>{rubric.map((item, index) => <div key={item.id ?? index}><input aria-label={`评分标准 ${index + 1}`} value={item.criterion} placeholder="例如：正确解释注意力权重" onChange={(event) => onChange(rubric.map((value, i) => i === index ? { ...value, criterion: event.target.value } : value))} /><input aria-label={`评分权重 ${index + 1}`} type="number" min="0" max="100" value={item.weight} onChange={(event) => onChange(rubric.map((value, i) => i === index ? { ...value, weight: Number(event.target.value) } : value))} /><button type="button" aria-label={`删除评分标准 ${index + 1}`} onClick={() => onChange(rubric.filter((_, i) => i !== index))}><Trash2 size={14} /></button></div>)}<button className="teacher-secondary-button" type="button" onClick={() => onChange([...rubric, { criterion: "", weight: 0 }])}><Plus size={14} />添加评分标准</button></fieldset>; }
function Empty({ text, compact = false }: { text: string; compact?: boolean }) { return <p className={compact ? "teacher-empty-inline" : "teacher-empty-state"}>{text}</p>; }
function SparkleMark() { return <span className="teacher-card-icon"><FilePlus2 size={16} /></span>; }

export function GuidedBlueprintCatalogEditor({ topics, blueprints = [], onChange }: { topics: CourseTopic[]; blueprints?: GuidedBlueprint[]; onChange: (items: GuidedBlueprint[]) => void }) {
  const [name, setName] = useState(""); const [topicId, setTopicId] = useState(""); const [pointId, setPointId] = useState(""); const [guidance, setGuidance] = useState("");
  const topicOptions = topics.filter((topic) => topic.status !== "disabled");
  const selectedTopic = topicOptions.find((topic) => topic.id === topicId);
  const points = selectedTopic?.knowledge_points.filter((point) => point.status === "enabled") ?? [];
  const create = () => { if (!name.trim() || !topicId || !pointId || !guidance.trim()) return; onChange([...blueprints, { id: makeId("guided"), name: name.trim(), topic_id: topicId, knowledge_point_id: pointId, guidance: guidance.trim(), status: "draft" }]); setName(""); setGuidance(""); };
  const update = (next: GuidedBlueprint) => onChange(blueprints.map((item) => item.id === next.id ? next : item));
  return <div className="teacher-stack"><section className="teacher-panel teacher-create-card"><header><div><span className="teacher-eyebrow">引导方向</span><h2>创建引导蓝图</h2><p>每张蓝图为一个知识点定义教师引导方向；学生进入引导模式时后端会随机抽取一张启用蓝图。</p></div></header>{topicOptions.length ? <div className="teacher-editor-grid"><div className="teacher-editor-two-column"><label>引导蓝图名称<input aria-label="guided蓝图名称" value={name} onChange={(event) => setName(event.target.value)} /></label><label>所属主题<select aria-label="guided所属主题" value={topicId} onChange={(event) => { setTopicId(event.target.value); setPointId(""); }}><option value="">选择主题</option>{topicOptions.map((topic) => <option value={topic.id} key={topic.id}>{topic.name}</option>)}</select></label></div><label>关联知识点<select aria-label="guided关联知识点" value={pointId} disabled={!topicId} onChange={(event) => setPointId(event.target.value)}><option value="">选择一个知识点</option>{points.map((point) => <option value={point.id} key={point.id}>{point.name}</option>)}</select></label><label>引导方向（Markdown 指令）<textarea aria-label="guidedMarkdown 指令" rows={6} value={guidance} onChange={(event) => setGuidance(event.target.value)} placeholder="说明教师希望模型采用的引导路径、提问顺序和应聚焦的误区。" /></label><button className="teacher-primary-button" type="button" disabled={!name.trim() || !topicId || !pointId || !guidance.trim()} onClick={create}><FilePlus2 size={16} />创建引导草稿蓝图</button></div> : <Empty text="请先创建并启用一个主题和知识点，才能创建蓝图。" />}</section><section className="teacher-panel"><header><div><h2>引导蓝图目录</h2><p>按主题与知识点组织；每张卡片定义一条引导方向。</p></div></header>{topics.map((topic) => <section className="teacher-blueprint-topic" aria-label={`主题：${topic.name}`} key={topic.id}><header><span className="teacher-topic-marker">主题</span><h3>{topic.name}</h3><span className="teacher-topic-meta">{topic.knowledge_points.length} 个知识点</span></header>{topic.knowledge_points.map((point) => { const items = blueprints.filter((item) => item.topic_id === topic.id && item.knowledge_point_id === point.id); return <section className="teacher-blueprint-point" key={point.id}><header><div><span className="teacher-point-marker">知识点</span><strong>{point.name}</strong></div><span>{items.length} 张蓝图</span></header>{items.length ? <div className="teacher-catalog-list">{items.map((item) => <GuidedBlueprintCard key={item.id} item={item} topics={topics} onChange={update} onRemove={() => onChange(blueprints.filter((value) => value.id !== item.id))} />)}</div> : <Empty text="该知识点暂未配置蓝图。" compact />}</section>; })}</section>)}</section></div>;
}

function GuidedBlueprintCard({ item, topics, onChange, onRemove }: { item: GuidedBlueprint; topics: CourseTopic[]; onChange: (item: GuidedBlueprint) => void; onRemove: () => void }) {
  const [expanded, setExpanded] = useState(false); const topic = topics.find((value) => value.id === item.topic_id); const allowedPoints = topic?.knowledge_points ?? [];
  return <article className={`teacher-catalog-card teacher-blueprint-card ${expanded ? "is-expanded" : ""}`}><div className="teacher-card-heading"><button className="teacher-card-toggle" type="button" aria-label={`${item.name || "蓝图"} ${expanded ? "收起" : "展开"}`} aria-expanded={expanded} onClick={() => setExpanded(!expanded)}><SparkleMark /><strong>{item.name || "未命名蓝图"}</strong><StatusBadge status={item.status} /></button><div className="teacher-card-actions"><StatusButton status={item.status} onChange={(status) => onChange({ ...item, status })} /><RemoveButton label={`引导蓝图“${item.name || "未命名"}”`} onRemove={onRemove} /></div></div>{expanded && <div className="teacher-editor-grid"><div className="teacher-editor-two-column"><label>蓝图名称<input value={item.name} onChange={(event) => onChange({ ...item, name: event.target.value })} /></label><label>所属主题<select value={item.topic_id} onChange={(event) => onChange({ ...item, topic_id: event.target.value, knowledge_point_id: "" })}>{topics.map((value) => <option value={value.id} key={value.id}>{value.name}</option>)}</select></label></div><label>关联知识点<select value={item.knowledge_point_id} onChange={(event) => onChange({ ...item, knowledge_point_id: event.target.value })}>{allowedPoints.map((point) => <option value={point.id} key={point.id}>{point.name}</option>)}</select></label><label>引导方向（Markdown 指令）<textarea rows={7} value={item.guidance} onChange={(event) => onChange({ ...item, guidance: event.target.value })} /></label></div>}</article>;
}
