import { AlertCircle, AlertTriangle, BarChart3, BookOpen, CheckCircle2, ChevronLeft, Clock3, FileQuestion, GraduationCap, LayoutDashboard, MessageCircleQuestion, RefreshCw, Save, Search, Sparkles, Target, Users } from "lucide-react";
import { useCallback, useEffect, useMemo, useState, type ReactNode } from "react";

import { BlueprintCatalogEditor, GuidedBlueprintCatalogEditor, TopicCatalogEditor } from "@/modules/teacher/workspace/TeacherCatalogManager";
import { SchoolLogo } from "@/shared/ui/SchoolLogo";
import { api, ensureAuth } from "@/platform/http/api";
import type { TeacherCatalog, TeacherOverview } from "@/shared/types";
import { resolveWorkspaceId } from "@/shared/utils/workspace";

export type TeacherPage = "overview" | "topics" | "exercises" | "reviews" | "guided" | "questions" | "reports";
const NAV: Array<{ page: TeacherPage; label: string; icon: typeof LayoutDashboard }> = [
  { page: "overview", label: "教师首页", icon: LayoutDashboard }, { page: "topics", label: "主题与知识点", icon: BookOpen },
  { page: "exercises", label: "出题蓝图", icon: Sparkles }, { page: "reviews", label: "复习蓝图", icon: Target }, { page: "guided", label: "引导模式", icon: MessageCircleQuestion },
  { page: "questions", label: "学生问题", icon: FileQuestion }, { page: "reports", label: "学习分析", icon: BarChart3 },
];
const pageFromPath = (): TeacherPage => { const candidate = location.pathname.split("/")[2] as TeacherPage; return NAV.some((item) => item.page === candidate) ? candidate : "overview"; };

function SaveActions({ saving, message, onSave }: { saving: boolean; message: string; onSave: () => void }) { return <div className="teacher-form-actions"><button type="button" disabled={saving} onClick={onSave}><Save size={16} />{saving ? "正在保存…" : "保存教学目录"}</button>{message && <span role="status">{message}</span>}</div>; }

function Overview({ data, catalog }: { data: TeacherOverview; catalog: TeacherCatalog }) { return <div className="teacher-stack"><section className="teacher-welcome"><div><span>TEACHER MODE</span><h1>NLP 教师空间</h1><p>在一个教学目录里维护主题、知识点与蓝图。学生端的可选主题和后端动态提示词都会使用这一份数据。</p></div><GraduationCap size={64} /></section><div className="teacher-kpis"><article><BookOpen /><span>教学主题</span><strong>{catalog.topics.length}</strong></article><article><Sparkles /><span>出题蓝图</span><strong>{catalog.exercise_blueprints.length}</strong></article><article><Target /><span>复习蓝图</span><strong>{catalog.review_blueprints.length}</strong></article><article><FileQuestion /><span>学生问题</span><strong>{data.summary.questions}</strong></article></div></div>; }

const difficultyText = { beginner: "入门", intermediate: "进阶", advanced: "深入" } as const;
const riskText = { low: "低风险", medium: "需关注", high: "高风险" } as const;
function formatQuestionTime(value: string) { const date = new Date(value); return Number.isNaN(date.getTime()) ? value : new Intl.DateTimeFormat("zh-CN", { month: "2-digit", day: "2-digit", hour: "2-digit", minute: "2-digit" }).format(date); }

function QuestionsPage({ data }: { data: TeacherOverview }) {
  const [query, setQuery] = useState(""); const [difficulty, setDifficulty] = useState("all");
  const questions = useMemo(() => data.questions.filter((item) => (difficulty === "all" || item.difficulty === difficulty) && `${item.question} ${item.topic} ${item.keywords.join(" ")}`.toLowerCase().includes(query.trim().toLowerCase())), [data.questions, difficulty, query]);
  return <div className="teacher-stack">
    <div className="teacher-page-summary"><div><span className="teacher-eyebrow">QUESTION INBOX</span><h2>把真实提问变成教学线索</h2><p>查看近 {data.period_days} 天学生在普通聊天中的问题，快速定位主题、难度和重复需求。</p></div><MessageCircleQuestion size={46} /></div>
    <div className="teacher-insight-kpis"><article><MessageCircleQuestion /><span>问题总数</span><strong>{data.summary.questions}</strong><small>近 {data.period_days} 天</small></article><article><Users /><span>活跃学生</span><strong>{data.summary.students}</strong><small>{data.summary.sessions} 个会话</small></article><article><BookOpen /><span>涉及主题</span><strong>{data.topic_distribution.length}</strong><small>按提问自动归类</small></article><article className={data.summary.error_questions ? "warning" : ""}><AlertCircle /><span>异常问题</span><strong>{data.summary.error_questions}</strong><small>执行失败或中断</small></article></div>
    <section className="teacher-panel"><header><div><h2>问题明细</h2><p>显示 {questions.length} / {data.questions.length} 条记录</p></div><div className="teacher-filters"><label><Search size={14} /><input aria-label="搜索学生问题" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="搜索问题、主题或关键词" /></label><select aria-label="筛选难度" value={difficulty} onChange={(event) => setDifficulty(event.target.value)}><option value="all">全部难度</option><option value="beginner">入门</option><option value="intermediate">进阶</option><option value="advanced">深入</option></select></div></header>
      {questions.length ? <div className="teacher-question-list">{questions.map((item) => <article key={item.turn_id}><div className="teacher-question-icon"><MessageCircleQuestion size={17} /></div><div className="teacher-question-body"><strong>{item.question}</strong><div className="teacher-question-meta"><span>{item.topic}</span><span className={`teacher-difficulty ${item.difficulty}`}>{difficultyText[item.difficulty]}</span><span>{item.question_type}</span>{item.has_error && <span className="error">异常</span>}</div>{item.keywords.length > 0 && <div className="teacher-tags">{item.keywords.map((keyword) => <span key={keyword}>#{keyword}</span>)}</div>}</div><small><Clock3 size={12} />{formatQuestionTime(item.created_at)}<b>{item.user_id}</b></small></article>)}</div> : <p className="teacher-empty-state">{data.questions.length ? "没有符合当前筛选条件的问题。" : "统计周期内还没有学生问题。"}</p>}
    </section>
  </div>;
}

function Distribution({ title, items, tone = "purple" }: { title: string; items: TeacherOverview["topic_distribution"]; tone?: "purple" | "blue" | "green" }) { return <section className="teacher-panel"><header><div><h2>{title}</h2><p>按问题数量汇总</p></div></header>{items.length ? <div className="teacher-distribution">{items.map((item) => <article key={item.name}><div><strong>{item.name}</strong><span>{item.count} 次 · {item.percentage}%</span></div><i><b className={tone} style={{ width: `${item.percentage}%` }} /></i></article>)}</div> : <p className="teacher-empty-inline">暂无分布数据</p>}</section>; }

function ReportsPage({ data }: { data: TeacherOverview }) {
  const maxScore = Math.max(1, ...data.weak_topics.map((item) => item.score));
  return <div className="teacher-stack">
    <div className="teacher-page-summary reports"><div><span className="teacher-eyebrow">LEARNING SIGNALS</span><h2>从提问证据发现薄弱项</h2><p>风险综合问题量、重复提问、难题与错误记录；它用于安排复习，不代表学生成绩。</p></div><BarChart3 size={46} /></div>
    <div className="teacher-insight-kpis"><article><Users /><span>覆盖学生</span><strong>{data.summary.students}</strong><small>{data.summary.sessions} 个会话</small></article><article><FileQuestion /><span>有效问题</span><strong>{data.summary.questions}</strong><small>分析样本总量</small></article><article className={data.weak_topics.some((item) => item.risk === "high") ? "warning" : ""}><AlertTriangle /><span>高风险主题</span><strong>{data.weak_topics.filter((item) => item.risk === "high").length}</strong><small>建议优先复习</small></article><article><CheckCircle2 /><span>低风险主题</span><strong>{data.weak_topics.filter((item) => item.risk === "low").length}</strong><small>继续观察</small></article></div>
    <section className="teacher-panel"><header><div><h2>主题风险雷达</h2><p>分数越高，越值得优先安排讲解或练习</p></div></header>{data.weak_topics.length ? <div className="teacher-risk-list">{data.weak_topics.map((item) => <article key={item.topic}><div className={`teacher-risk-mark ${item.risk}`}><AlertTriangle size={16} /></div><div><div className="teacher-risk-heading"><strong>{item.topic}</strong><span className={item.risk}>{riskText[item.risk]}</span><b>{item.score}</b></div><i><b className={item.risk} style={{ width: `${Math.max(8, item.score / maxScore * 100)}%` }} /></i><p>{item.questions} 个问题 · {item.repeat_questions} 次重复 · {item.errors} 次错误 · {item.sessions} 个会话</p></div></article>)}</div> : <p className="teacher-empty-state">暂无足够学习证据生成薄弱项。</p>}</section>
    <div className="teacher-report-grid"><Distribution title="主题分布" items={data.topic_distribution} /><Distribution title="难度分布" items={data.difficulty_distribution} tone="blue" /><Distribution title="题型分布" items={data.type_distribution} tone="green" /></div>
    {data.frequent_questions.length > 0 && <section className="teacher-panel"><header><div><h2>高频问题</h2><p>重复出现的问题适合转化为讲解或复习素材</p></div></header><div className="teacher-frequent">{data.frequent_questions.slice(0, 6).map((item) => <article key={`${item.topic}-${item.question}`}><b>{item.count}</b><span><strong>{item.question}</strong><small>{item.topic} · {item.question_type}</small></span></article>)}</div></section>}
  </div>;
}

export function TeacherWorkspace({ page: routedPage, onNavigate }: { page?: TeacherPage; onNavigate?: (page: TeacherPage) => void }) {
  const [page, setPage] = useState<TeacherPage>(routedPage ?? pageFromPath); const [data, setData] = useState<TeacherOverview | null>(null); const [catalog, setCatalog] = useState<TeacherCatalog | null>(null); const [workspaceId, setWorkspaceId] = useState("default"); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState(""); const [saveMessage, setSaveMessage] = useState("");
  const activePage = routedPage ?? page;
  const load = useCallback(async () => { setLoading(true); setError(""); try { const auth = await ensureAuth(); if (!auth.roles.some((role) => role === "admin" || role === "teacher")) throw new Error("当前账户没有教师权限"); const settings = await api.getSettings(); const selectedWorkspaceId = resolveWorkspaceId(auth, settings.preferences.settings ?? {}); const [overview, catalogResult] = await Promise.all([api.getTeacherOverview(selectedWorkspaceId), api.getTeacherCatalog(selectedWorkspaceId)]); setWorkspaceId(selectedWorkspaceId); setData(overview); setCatalog({ ...catalogResult.catalog, guided_blueprints: catalogResult.catalog.guided_blueprints ?? [] }); } catch (reason) { setError(reason instanceof Error ? reason.message : String(reason)); } finally { setLoading(false); } }, []);
  useEffect(() => { queueMicrotask(() => void load()); }, [load]);
  const save = useCallback(async () => { if (!catalog) return; setSaving(true); setSaveMessage(""); try { const result = await api.updateTeacherCatalog(workspaceId, { topics: catalog.topics, exercise_blueprints: catalog.exercise_blueprints, review_blueprints: catalog.review_blueprints, guided_blueprints: catalog.guided_blueprints }); setCatalog(result.catalog); setSaveMessage("已保存并同步到后端。"); } catch (reason) { setSaveMessage(`保存失败：${reason instanceof Error ? reason.message : String(reason)}`); } finally { setSaving(false); } }, [catalog, workspaceId]);
  const navigate = (next: TeacherPage) => { if (onNavigate) onNavigate(next); else { history.pushState({}, "", next === "overview" ? "/teacher" : `/teacher/${next}`); setPage(next); } };
  const editable = (children: ReactNode) => <>{children}<SaveActions saving={saving} message={saveMessage} onSave={() => void save()} /></>;
  const content = !data || !catalog ? null : activePage === "topics" ? editable(<TopicCatalogEditor topics={catalog.topics} onChange={(topics) => { setCatalog({ ...catalog, topics }); setSaveMessage(""); }} />) : activePage === "exercises" ? editable(<BlueprintCatalogEditor kind="exercise" topics={catalog.topics} blueprints={catalog.exercise_blueprints} exerciseBlueprints={catalog.exercise_blueprints} onChange={(exercise_blueprints) => { setCatalog({ ...catalog, exercise_blueprints: exercise_blueprints as TeacherCatalog["exercise_blueprints"] }); setSaveMessage(""); }} />) : activePage === "reviews" ? editable(<BlueprintCatalogEditor kind="review" topics={catalog.topics} blueprints={catalog.review_blueprints} exerciseBlueprints={catalog.exercise_blueprints} onChange={(review_blueprints) => { setCatalog({ ...catalog, review_blueprints: review_blueprints as TeacherCatalog["review_blueprints"] }); setSaveMessage(""); }} />) : activePage === "guided" ? editable(<GuidedBlueprintCatalogEditor topics={catalog.topics} blueprints={catalog.guided_blueprints} onChange={(guided_blueprints) => { setCatalog({ ...catalog, guided_blueprints }); setSaveMessage(""); }} />) : activePage === "questions" ? <QuestionsPage data={data} /> : activePage === "reports" ? <ReportsPage data={data} /> : <Overview data={data} catalog={catalog} />;
  return <div className="teacher-shell"><aside className="teacher-nav"><div className="teacher-brand"><GraduationCap /><span><strong>NLP 教师空间</strong><small>Teacher workspace</small></span><button type="button" onClick={() => void load()} disabled={loading}><RefreshCw className={loading ? "spin" : ""} size={15} />刷新</button></div><nav>{NAV.map(({ page: itemPage, label, icon: Icon }) => <button className={activePage === itemPage ? "active" : ""} type="button" key={itemPage} onClick={() => navigate(itemPage)}><Icon size={17} />{label}</button>)}</nav><a href="/"><ChevronLeft size={16} />返回学生模式</a></aside><main className="teacher-main"><header className="teacher-topbar"><div><h1>{NAV.find((item) => item.page === activePage)?.label}</h1><span>{workspaceId} workspace · 目录修改需保存后生效</span></div><div className="teacher-topbar-actions"><SchoolLogo /></div></header><div className="teacher-content">{loading ? <div className="teacher-state"><RefreshCw className="spin" />正在加载教学目录…</div> : error ? <div className="teacher-state error"><AlertCircle /><strong>无法进入教师模式</strong><p>{error}</p></div> : content}</div></main></div>;
}
