"""Human-readable comments for the MySQL tables managed by the application."""

from __future__ import annotations


# Keep these comments short enough for MySQL's table comment limit while making
# the purpose of every table visible in database administration tools.
TABLE_COMMENTS: dict[str, str] = {
    "nlp_users": "用户账户、认证摘要、显示名称与启用状态。",
    "nlp_roles": "RBAC 角色定义及角色状态。",
    "nlp_permissions": "RBAC 权限目录，描述可执行的领域、资源与操作。",
    "nlp_user_roles": "用户与角色的绑定关系及有效期。",
    "nlp_feedback_threads": "学生意见反馈会话，按用户聚合反馈线程。",
    "nlp_feedback_messages": "反馈会话中的逐条消息与发送方类型。",
    "nlp_role_permissions": "角色与权限的授权关系。",
    "nlp_role_permission_scopes": "角色权限对应的资源作用域类型。",
    "nlp_workspace_members": "用户与工作区的成员关系及成员状态。",
    "nlp_authorization_audit_logs": "授权判定与 RBAC 管理操作的追加式审计记录。",
    "nlp_classrooms": "工作区对应的课堂定义。",
    "nlp_classroom_members": "课堂与用户的成员关系及课堂内角色。",
    "nlp_class_join_requests": "课堂加入申请与审批流转（用户管理）。",
    "nlp_menus": "前端菜单树、路由和可见性配置。",
    "nlp_role_menus": "角色可见菜单的关联关系。",
    "nlp_workspaces": "租户或工作区的基本信息及状态。",
    "nlp_sessions": "登录会话、令牌摘要、CSRF 摘要及过期/撤销状态。",
    "nlp_auth_codes": "图形/短信一次性验证码的哈希存储，含过期时间与发送频控记录。",
    "nlp_sms_send_audits": "短信发送审计记录，独立于可消费的一次性验证码保存，用于可靠频控。",
    "nlp_pricing_rules": "按 pricing_key 版本化保存 Token 和功能单位的 Credits 换算规则。",
    "nlp_usage_events": "不可变 Token/功能用量、归属、状态与 Shadow Credits 事实。",
    "nlp_quota_policies": "开发者配置的版本化额度策略及请求、周期、并发和模型限制。",
    "nlp_quota_policy_bindings": "额度策略与默认、角色、工作区或用户主体的绑定。",
    "nlp_quota_buckets": "用户、工作区或课堂每日/每周额度的原子消耗与预占计数器。",
    "nlp_quota_concurrency_locks": "按用户维护的并发租约原子计数器，跨进程保护额度并发限制。",
    "nlp_quota_reservations": "Turn 级额度预占、结算状态及并发租约。",
    "nlp_quota_ledger_entries": "额度预占、释放和实际结算的追加式会计流水。",
    "nlp_quota_grants": "用户、工作区或课堂的可追溯额度分配及撤销状态。",
    "nlp_quota_adjustments": "带操作人、原因和幂等键的手工额度调整流水。",
    "nlp_quota_credit_operations": "赠送与重置 Credits 的幂等操作意图和结果。",
    "nlp_quota_role_credit_operations": "按角色向成员批量赠送 Credits 的幂等批次记录。",
    "nlp_quota_credit_scope_locks": "按额度主体周期串行化赠送和重置操作的持久化锁。",
    "nlp_quota_daily_rollups": "脱离 Turn 主链路生成的每日 Token 与 Credits 聚合。",
    "nlp_quota_provider_billing": "Provider 账单行、UsageEvent 匹配结果与差异。",
    "nlp_quota_usage_archive_batches": "UsageEvent 非破坏性归档批次清单。",
    "nlp_quota_alerts": "基于用量聚合生成的突增和异常消费告警。",
    "nlp_ws_tickets": "绑定登录会话的一次性 WebSocket 连接票据。",
    "nlp_teaching_goals": "工作区教学目标及其版本号。",
    "nlp_course_catalogs": "工作区课程目录的当前版本指针。",
    "nlp_course_topics": "课程目录中的主题或章节。",
    "nlp_knowledge_points": "主题下的知识点内容。",
    "nlp_knowledge_pages": "知识点教材正文的草稿与已发布版本。",
    "nlp_knowledge_book_assets": "知识教材批量导入后经过校验的图片资源。",
    "nlp_teaching_blueprints": "教学或练习蓝图及其载荷版本。",
    "nlp_blueprint_rubrics": "蓝图评分标准、权重与排序。",
    "nlp_course_catalog_versions": "课程目录发布版本的完整快照。",
    "nlp_conversations": "工作区内用户对话及其状态。",
    "nlp_turns": "对话执行轮次的输入输出、状态与处理租约。",
    "nlp_conversation_messages": "对话消息的有序持久化内容。",
    "nlp_turn_events": "执行轮次的顺序事件和事件载荷。",
    "nlp_exercise_sessions": "用户练习会话及蓝图快照。",
    "nlp_exercise_questions": "练习会话中的题目和评分规则。",
    "nlp_exercise_attempts": "用户练习作答、评分结果与反馈。",
    "nlp_learning_evidence": "练习完成后沉淀的学习证据。",
    "nlp_guided_sessions": "基于知识点的引导式学习会话状态。",
    "nlp_user_preferences": "用户级前端或学习偏好及版本号。",
    "nlp_outbox_messages": "待发布的可靠消息及投递重试状态。",
    "nlp_turn_cancellations": "对执行轮次的取消请求。",
    "nlp_tool_calls": "工具调用的幂等记录、请求结果与状态。",
    "nlp_dead_letters": "处理失败后进入死信队列的消息。",
    "nlp_agent_checkpoints": "Agent 会话检查点及其元数据快照。",
    "nlp_langgraph_checkpoints": "LangGraph 检查点的序列化主记录。",
    "nlp_langgraph_checkpoint_blobs": "LangGraph 检查点 channel 值的二进制版本数据。",
    "nlp_langgraph_checkpoint_writes": "LangGraph 检查点的任务写入记录。",
    "nlp_conversation_transcripts": "会话历史消息与工具内容的转录存档。",
    "nlp_memory_documents": "用户工作区的长期记忆文档。",
    "nlp_release_notes": "面向开发者和学生的版本发布说明。",
    "nlp_memory_archives": "记忆归档事件及其来源游标。",
    "nlp_memory_cursors": "记忆消费范围的全局游标。",
    "nlp_tool_audits": "工具执行审计及请求/结果快照。",
    "nlp_runtime_config_versions": "按作用域保存的运行时配置版本快照。",
    "nlp_observability_records": "trace、span 与 telemetry 的统一可观测性记录。",
    "nlp_sandbox_environments": "每位用户唯一的逻辑沙箱归属与配置版本，不保存代码。",
    "nlp_sandbox_runtime_instances": "沙箱运行实例声明与健康状态；Phase 0 不创建容器。",
    "nlp_sandbox_leases": "认证会话绑定的沙箱租约、过期与撤销状态。",
    "nlp_sandbox_executions": "沙箱执行的最小审计摘要，不保存代码或标准输出。",
    "nlp_sandbox_artifacts": "沙箱产物的受控存储指针与过期信息。",
}


SYSTEM_TABLE_COMMENTS: dict[str, str] = {
    "alembic_version": "Alembic 数据库迁移版本记录，不承载业务数据。",
}
