"""Safe delivery contract for untrusted sandbox artifacts on a separate origin."""

from __future__ import annotations

import base64
import hashlib
import hmac
import json
import time
from datetime import timedelta
from pathlib import Path
from urllib.parse import quote


class ArtifactAccessSigner:
    """Issue short-lived, owner-bound access tickets for the artifact origin."""

    def __init__(self, secret: str, *, lifetime: timedelta = timedelta(minutes=5)) -> None:
        self._secret = secret.encode("utf-8")
        self._lifetime = lifetime

    def issue(self, *, artifact_id: str, owner_user_id: str) -> str:
        payload = json.dumps(
            {
                "a": artifact_id,
                "u": owner_user_id,
                "e": int(time.time() + self._lifetime.total_seconds()),
            },
            separators=(",", ":"),
            sort_keys=True,
        ).encode("utf-8")
        encoded = base64.urlsafe_b64encode(payload).rstrip(b"=")
        signature = hmac.new(self._secret, encoded, hashlib.sha256).hexdigest()
        return f"{encoded.decode('ascii')}.{signature}"

    def verify(self, ticket: str, *, artifact_id: str, owner_user_id: str) -> None:
        try:
            encoded, signature = ticket.split(".", maxsplit=1)
            expected = hmac.new(self._secret, encoded.encode("ascii"), hashlib.sha256).hexdigest()
            padding = "=" * (-len(encoded) % 4)
            payload = json.loads(base64.urlsafe_b64decode(encoded + padding))
        except (UnicodeEncodeError, ValueError, json.JSONDecodeError) as error:
            raise PermissionError("invalid sandbox artifact ticket") from error
        if not hmac.compare_digest(signature, expected):
            raise PermissionError("invalid sandbox artifact ticket")
        if payload.get("a") != artifact_id or payload.get("u") != owner_user_id:
            raise PermissionError("sandbox artifact ticket does not match the requested artifact")
        if not isinstance(payload.get("e"), int) or payload["e"] < time.time():
            raise PermissionError("sandbox artifact ticket expired")


def artifact_access_url(origin: str, *, artifact_id: str, ticket: str) -> str:
    """Build a ticketed URL on the dedicated artifact origin."""
    if not origin.startswith(("https://", "http://")):
        raise ValueError("sandbox artifact origin must be an absolute HTTP(S) URL")
    return f"{origin.rstrip('/')}/api/v1/sandbox/artifacts/{quote(artifact_id, safe='')}/content?ticket={quote(ticket, safe='')}"


def resolve_artifact_path(store_root: Path, locator: str) -> Path:
    """Resolve a database locator without allowing traversal or symlink escape."""
    relative = Path(locator)
    if relative.is_absolute() or ".." in relative.parts:
        raise PermissionError("sandbox artifact locator escapes the configured store")
    root = store_root.resolve(strict=True)
    candidate = (root / relative).resolve(strict=True)
    try:
        candidate.relative_to(root)
    except ValueError as error:
        raise PermissionError("sandbox artifact locator escapes the configured store") from error
    if not candidate.is_file():
        raise PermissionError("sandbox artifact locator is not a regular file")
    return candidate

def artifact_security_headers(mime_type: str) -> dict[str, str]:
    """Headers required when artifact origin serves HTML/SVG generated by code."""
    csp = "default-src 'none'; script-src 'none'; connect-src 'none'; object-src 'none'; base-uri 'none'; form-action 'none'; img-src data: blob:; style-src 'unsafe-inline'; sandbox"
    if mime_type not in {"text/html", "image/svg+xml"}:
        csp = "default-src 'none'; sandbox"
    return {
        "Content-Security-Policy": csp,
        "Cross-Origin-Resource-Policy": "cross-origin",
        "X-Content-Type-Options": "nosniff",
        "Referrer-Policy": "no-referrer",
    }
